### ISSUE TITLE
Design patterns should be more mobile friendly

### ISSUE THREAD

**Issue by daileytj** [pxblue/ionic-design-patterns#4]
#### Describe the desired behavior
Design patterns should use components better suited for mobile devices.

#### Describe the current behavior
Design patterns are occasionally using components that are better suited for a web browser rather than a mobile device.

#### Additional Context

- Action List
  - use bottomsheet instead of mat-menu
- Multiselect List
  - Pseudo bottom sheet should animate in from the bottom instead of the side
  - Bottom sheet should cover unsafe area while keeping text/icons in the safearea
- Sortable List
  - Should use icon buttons instead of text button for sort toggle

**Comment by huayunh** [comment]
Might need some design work on this... moving to Jira so that we can have some integrated task force on these problems

**Comment by jeffvg** [comment]
moved to PXBLUE-1930
